mymongodb:
    image: mongo
    ports: 
    - "27017:27017"
web:
   image: maccam912/meanjs
   links:
   - mymongodb:db_1
   ports:
   - "3000:3000"
   environment: 
   - "NODE_ENV:development"
   command: bash -c "./get_latest_and_build.sh && grunt"


