web:
   image: maccam912/meanjs
   links:
    - mymongodb:db_1
   ports:
    - "3000:3000"
   command: bash -c "cd Development && git clone https://github.com/dreamerkumar/meanjs.git && cd meanjs && chmod 777 ./build_source_files.sh && ./build_source_files.sh"
mymongodb:
    image: mongo